services:
  - type: web
    name: studymind-api
    runtime: image
    repo: https://github.com/UzairRan/StudyMind-AI
    branch: main
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: GEMINI_API_KEY
        sync: false
    autoDeploy: true 